---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь может удалять товары из корзины
  - Пользователь может оформлять заказ с переходом на страницу оплаты
  - На странице товара и в каталоге отображается - название, рейтинг, цена со скидкой и без неё
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен иметь мобильную версию
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Подсчет общей суммы в корзине с учетом скидок
  - Возможность изменить количество товара в корзине
  - Восстановление корзины при перезагрузке страницы
  - Валидация данных (например, проверка корректности цены, наличия товара)
  - Возможность интеграции с платежными системами
  - Выводится список товаров
  - У каждого товара указана цена
  - У каждого товара есть кнопка для заказа товара
  - Выводится список заказов
  - Для каждого заказа выводится дата заказа
  - Для каждого заказа выводится общая сумма заказа
  - Для каждого заказа есть кнопка для подробного просмотра заказа
  - Выводится номер заказа
  - Выводится список заказанных товаров
  - Для каждого товара выводится название, цена, количество
  - Выводится общая сумма